netty.port: 8000
business.thread.count: 100
proxy.registry.address: zookeeper://127.0.0.1:2181
proxy.registry.group: dubbo
proxy.metadata-report.address: zookeeper://127.0.0.1:2181



mapping:
  services:
   -
    name: demoservice
    interfaze: org.apache.dubbo.api.DemoService
    group: test
    version: 1.0.0
